package search

import "os"

// Searcher is the query surface shared by the two index implementations.
//
// Index is the vector index: it ships prebuilt in the binary and uses OpenAI
// embeddings, giving semantic matches. FTS is a SQLite keyword index built
// locally, used when there is no OpenAI key so that search still works.
type Searcher interface {
	Store(md map[string]string, content ...string) error
	Query(q string) ([]*Result, error)
}

// Semantic reports whether the vector index can be used. Embeddings are
// generated by OpenAI, so without a key the keyword index is used instead.
func Semantic() bool {
	return os.Getenv("OPENAI_API_KEY") != ""
}
